feat: add v custom build
nitrictech/docs pull request #103
Opened 2021-09-27 04:27 UTC by medgar-nitric

2021-09-27 04:30 UTC, tjholm reviewed
I think Jye had some interesting configuration comparisons for this, like cloudformation vs. nitric.yaml to really showcase the difference in volume of configuration and knowledge required as well.

2021-09-27 05:58 UTC, medgar-nitric commented
> I think Jye had some interesting configuration comparisons for this, like cloudformation vs. nitric.yaml to really showcase the difference in volume of configuration and knowledge required as well.

Sounds good if you want to add that content, that would be great.

2021-09-27 23:05 UTC, HomelessDinosaur commented on docs/intro/vs/custom.mdx
> +- supports multi development languages
multi -> multiple

2021-09-27 23:05 UTC, HomelessDinosaur commented on docs/intro/vs/custom.mdx
> +Making the choice for Custom Build over Nitric will prematurely reduces Optionality for the business, this may include:
reduces -> reduce

2021-09-27 23:05 UTC, HomelessDinosaur commented on docs/intro/vs/custom.mdx
> +- only supporting one Cloud vendor, limiting future business sales options and reduces cloud pricing control
, limiting -> limits ?

2021-09-27 23:41 UTC, davemooreuws requested changes

2021-09-27 23:41 UTC, davemooreuws commented on docs/intro/vs/custom.mdx
> +- difficulty of attracting the require development staff
require -> required

2021-09-28 00:09 UTC, HomelessDinosaur approved these changes

2021-10-05 01:45 UTC, davemooreuws approved these changes

2021-10-05 02:32 UTC, merged