feat: update events docs
nitrictech/docs pull request #106
Opened 2021-09-27 06:03 UTC by jyecusch

2021-09-27 06:06 UTC, tjholm requested changes

2021-09-27 06:06 UTC, tjholm commented on docs/reference/api/events/subscribe.mdx
> +services:
functions

2021-09-27 06:10 UTC, tjholm commented on docs/reference/api/events/subscribe.mdx
> +        - user-registered
I think this is a good example of duplicate content (a positive example that is), where the api section provides a call to action, but this same content will also appear under the function/container references in the project configuration above (as documented properties of those resources). But in this case we can just provide a link from the trigger property as well.

2021-09-27 06:23 UTC, HomelessDinosaur commented on docs/reference/api/events/publish.mdx
> +When implementing design patterns that allow for atomic state changes and event publishing, such as [Transactional Outbox](https://microservices.io/patterns/data/transactional-outbox.html), it's crit
depulicate -> duplicate

2021-09-27 07:07 UTC, tjholm approved these changes

2021-09-27 07:17 UTC, jyecusch commented on docs/reference/api/events/publish.mdx
> +When implementing design patterns that allow for atomic state changes and event publishing, such as [Transactional Outbox](https://microservices.io/patterns/data/transactional-outbox.html), it's crit
fixed

2021-09-27 12:41 UTC, medgar-nitric requested changes
Looks good, just minor typo.

2021-09-27 12:41 UTC, medgar-nitric commented on docs/reference/api/events/_index.mdx
>  - **Subscribers** are consumers of events, typically in the form of a request that must handled.
must **be** handled.

2021-09-27 21:27 UTC, jyecusch commented on docs/reference/api/events/_index.mdx
>  - **Subscribers** are consumers of events, typically in the form of a request that must handled.
fixed

2021-09-28 04:48 UTC, jyecusch commented on docs/reference/api/events/subscribe.mdx
> +        - user-registered
fixed

2021-09-29 03:41 UTC, davemooreuws approved these changes

2021-09-30 05:19 UTC, tjholm approved these changes

2021-09-30 05:23 UTC, medgar-nitric commented on docs/reference/api/events/_index.mdx
There are other benefits of pub/sub architectures, temporal decoupling, load leveling, efficient resource use, etc., but this is probably not the righ place to go into all this.

2021-09-30 05:29 UTC, medgar-nitric approved these changes

2021-09-30 07:24 UTC, merged