Feat/azure reference
nitrictech/docs pull request #200
Opened 2022-02-10 18:01 UTC by raksiv

2022-02-10 22:21 UTC, tjholm requested changes

2022-02-10 22:21 UTC, tjholm commented on docs/reference/azure/apis.mdx
> +- App Service Functions
We're using Container Apps now (they're currently in preview so we'll need to add that caveat), if we're clever we'll eventually write plugins that hook into their Dapr operator to do our other stuff as well i.e. PubSub.

2022-02-13 21:31 UTC, tjholm commented on docs/reference/azure/collections.mdx
> +- The topic defintion and resource group are deployed as a MongoDB Collection.
topic -> collection.

defintion -> definition

2022-02-13 22:00 UTC, davemooreuws commented
Should this really be under reference?

2022-02-16 02:46 UTC, tjholm approved these changes

2022-02-16 04:16 UTC, davemooreuws approved these changes

2022-02-16 04:16 UTC, merged