chore: first draft of profiles tutorial
nitrictech/docs pull request #244
Opened 2022-03-02 03:04 UTC by raksiv

2022-03-21 05:11 UTC, jyecusch requested changes

2022-03-21 22:24 UTC, raksiv commented on docs/guides/profiles.md
> +| `PUT`      | /profiles/{$profileId} | Update a profile                 |
Updated to {id}

2022-03-21 22:24 UTC, raksiv commented on docs/guides/profiles.md
> +| `GET`      | profiles/{id}/image/download | Get a profile image download URL |
Updated to same as above.

2022-03-21 22:24 UTC, raksiv commented on docs/guides/profiles.md
> +? Choose a template: official/TypeScript - Starter
Updated with new CLI output.

2022-03-21 22:24 UTC, raksiv commented on docs/guides/profiles.md
> ++--package.json
Updated filepath to reintroduce nitric.yaml.

2022-03-21 22:25 UTC, raksiv commented on docs/guides/profiles.md
> +- a collection named profiles with reading/writing permissions
Done, reversed order for more clarity.

2022-03-21 22:25 UTC, raksiv commented on docs/guides/profiles.md
> +```
Removed the profile interface from use.

2022-03-21 22:25 UTC, raksiv commented on docs/guides/profiles.md
> +  const id = ctx.req.params['id'];
Done, across all examples.

2022-03-21 22:26 UTC, raksiv commented on docs/guides/profiles.md
> +    const profile = await profiles.doc(id).delete();
Removed variable assignment and await

2022-03-21 22:26 UTC, raksiv commented on docs/guides/profiles.md
> +    return ctx.res.json(profile);
Removed return.

2022-03-25 03:59 UTC, jyecusch approved these changes

2022-03-25 04:15 UTC, tjholm approved these changes

2022-03-25 04:15 UTC, merged