Feature/react app tutorial
nitrictech/docs pull request #25
Opened 2021-06-24 04:26 UTC by HomelessDinosaur

2021-06-24 07:02 UTC, tjholm requested changes

2021-06-24 07:02 UTC, tjholm commented on docs/tutorials/create-react-app.mdx
> +If we now use our `nitric run` command we should get a URL at the bottom. If we go to this URL in our browser it will open up into our app.
This tutorial is awesome :). My only suggestion would be to add a screen capture of the final result.

2021-06-24 07:07 UTC, tjholm commented
Have updated the nitric-website repo with the menu item to access this doc, if you check it out you should be able to demo it at: feature/create-react-app.

@davemooreuws Is looking at porting the docs config to this repo at some point to help remove the separation between that config and this repo.

2021-06-29 02:54 UTC, davemooreuws commented
I will merge this into another branch with the nextjs tutorial, so we can ensure they are consistent.

2021-06-29 02:54 UTC, closed without merging