Feat/supabase funcs guide
nitrictech/docs pull request #258
Opened 2022-03-25 21:56 UTC by jyecusch

2022-03-25 21:59 UTC, tjholm requested changes
Just one typo, other than that looks good

2022-03-25 21:59 UTC, tjholm commented on docs/guides/nitric-and-supabase.md
> +That it!
That's it!

2022-03-25 22:02 UTC, jyecusch commented on docs/guides/nitric-and-supabase.md
> +That it!
Fixed

2022-03-26 05:15 UTC, davemooreuws approved these changes
Pushed a change to ensure relative urls for docs. Looks good.

2022-03-26 08:51 UTC, raksiv commented
Ran through the demo - looked good.

2022-03-26 08:51 UTC, raksiv approved these changes

2022-03-27 07:22 UTC, merged