feat: Add integration testing guide
nitrictech/docs pull request #264
Opened 2022-03-29 06:23 UTC by HomelessDinosaur

2022-03-29 22:45 UTC, davemooreuws requested changes
Really nice doc. Just a few typos and suggestion.

2022-03-29 22:45 UTC, davemooreuws commented on docs/reference/tests/_index.mdx
> +We attempt to make the local run of nitric as similar as possible as the cloud environments, so these tests should act the same locally as they do the cloud. However, running them on the cloud may in
"as similar as possible as the cloud environments" to "as similar as possible to the cloud environments"?

2022-03-29 22:45 UTC, davemooreuws commented on docs/reference/tests/integration-testing.mdx
> +To invoke our tests we can do `yarn test` locally. This will run the tests against the deployed instance and return you your test results.
remove the word you

2022-03-29 22:45 UTC, davemooreuws commented on docs/reference/tests/integration-testing.mdx
> +Now for testing. The obvious first step before testing is to [deploy](https://nitric.io/docs/getting-started#deploying-the-app) the API. Then, to test against the deployed API, we just want to swap o
before running our tests is to, suggestion

2022-03-29 22:50 UTC, davemooreuws approved these changes

2022-03-30 00:44 UTC, raksiv commented on docs/reference/tests/integration-testing.mdx
> +There are two options for running our tests.
Suggestion - change . to :

2022-03-30 00:47 UTC, raksiv commented on docs/reference/tests/integration-testing.mdx
> +Integration tests are important for your systems as they catch system-level issues that unit tests miss, whilst being faster than end-to-end tests.
Suggestion - Change whilst to american english 'while' or just simple 'and are faster...'

2022-03-30 00:48 UTC, raksiv commented on docs/reference/tests/integration-testing.mdx
> +
Suggestion Add links out to the description website of jest and supertest

2022-03-30 00:49 UTC, raksiv commented on docs/reference/tests/integration-testing.mdx
> +To invoke our tests we can do `yarn test` locally. This will run the tests against the deployed instance and return your test results.
Might be worth showing them what this looks like as output.

2022-03-30 00:50 UTC, raksiv approved these changes
Approved with non blocking suggestions -

2022-03-31 00:26 UTC, merged