feat: add twilio guide
nitrictech/docs pull request #283
Opened 2022-04-11 06:55 UTC by HomelessDinosaur

2022-04-27 04:10 UTC, tjholm requested changes

2022-04-27 04:10 UTC, tjholm commented on docs/guides/twilio.md
> +curl -X POST -d '{"to":"+6141234567", "message": "Test Message from Twilio!"}' http://localhost:9001/apis/text/send
I'd probably use USA country code over Aus in this case

2022-04-27 04:10 UTC, tjholm commented on docs/guides/twilio.md
> +  "to": "+61412345678",
change to use USA country code.

2022-05-03 01:35 UTC, tjholm approved these changes

2022-05-03 01:47 UTC, davemooreuws approved these changes

2022-05-03 01:47 UTC, davemooreuws commented
@HomelessDinosaur just a conflict here

2022-05-03 04:15 UTC, merged