chore: first commit
nitrictech/docs pull request #318
Opened 2022-08-15 22:20 UTC by raksiv

Adding deploy guide with all screenshots

2022-08-15 23:07 UTC, elisselockhart reviewed
Added a few suggestions @raksiv

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +> Nitric Deploy is currently in Alpha, you'll need to [request access](https://deploy.nitric.io/signup).
change "Alpha" to "preview" ?

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +> Your email address will need to match your github account.
Instead of making this a second alert, could you just add it after an "and" in the sentence above?

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +> Nitric Deploy is currently in Alpha, you'll need to [request access](https://deploy.nitric.io/signup).
The comma in the middle of this should be a period. 

Let's also make the second sentence, "[Request access](https://deploy.nitric.io/signup) using your Github account email address."

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +> Your email address will need to match your github account.
Actually, would suggest altering it as I suggested in the previous comment.

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +Existing projects have either been scaffolded by Nitric Deploy or have been created using the Nitric CLI.
This might be just non-technical person feedback, but this sentence isn't totally clear to me.

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +Existing projects have either been scaffolded by Nitric Deploy or have been created using the Nitric CLI.
Is it "In order to import an existing project, it must have been either scaffolded by..." ?

2022-08-15 23:07 UTC, elisselockhart commented on docs/guides/deploy.md
> +
Add a wrap-up sentence... something like this?

"That's it! With just a few easy clicks, you've deployed a project to your cloud and don't have to manage environments or infrastructure state."

2022-08-16 00:39 UTC, jyecusch requested changes
@raksiv can you squash these commits into a single `feat` commit? I also replaced the images to remove the watermark and increase the resolution a bit.

2022-08-16 13:28 UTC, raksiv commented on docs/guides/deploy.md
> +- Updating your code and pushing to the configured branch
Updated

2022-08-16 13:29 UTC, raksiv commented on docs/guides/deploy.md
> +- Get started on one of our [guides](/docs/reference)
Updated

2022-08-16 13:30 UTC, raksiv commented on docs/guides/deploy.md
> +Try one of the following activities to keep going with Nitric
Updated.

2022-08-16 13:30 UTC, raksiv commented on docs/guides/deploy.md
> +1. Sign to Nitric Deploy
Updated

2022-08-16 13:30 UTC, raksiv commented on docs/guides/deploy.md
> +
Updated

2022-08-16 16:28 UTC, elisselockhart approved these changes

2022-08-17 04:41 UTC, jyecusch approved these changes

2022-08-17 04:47 UTC, merged