wip: first version of python guide
nitrictech/docs pull request #348
Opened 2022-11-08 21:51 UTC by raksiv

This is currently in a single file

2022-11-08 22:04 UTC, tjholm reviewed
Looks awesome! Providing some guidance on caching might be good, but could also be a separate guide or best practice document.

2022-11-08 23:40 UTC, raksiv commented on docs/guides/serverless-rest-api-example.md
> +```
Sounds good, I'll make the update to both guides.

2022-11-09 18:21 UTC, raksiv commented on docs/guides/serverless-rest-api-example.md
> +```
Lets sync up so I can get more info about this one

2022-11-09 18:22 UTC, raksiv commented on docs/guides/serverless-rest-api-example.md
> +```
Are you thinking something like this - 

    photo_url = await photo.sign_url(mode=FileMode.WRITE, expiry=3600)

    expires = datetime.utcnow() + timedelta(seconds=(3600))
    expires = expires.strftime("%a, %d %b %Y %H:%M:%S GMT")
    ctx.res.headers['Expires'] = expires

2022-11-09 18:23 UTC, raksiv commented on docs/guides/serverless-rest-api-example.md
> +```
And changing the 303 to 307?

2022-11-10 23:32 UTC, tjholm commented on docs/guides/serverless-rest-api-example.md
> +```
Not sure if changing the redirect code is required, haven't looked at the behaviour of expires for `303`, worth trying without changing it and monitoring browser to see what happens on subsequent requests.

2022-11-14 05:19 UTC, jyecusch requested changes

2022-11-14 05:19 UTC, jyecusch commented on docs/guides/serverless-rest-api-example.md
> +from nitric.api.storage import FileMode
This import isn't needed, we can use the `file.upload_url()` and `file.download_url()` methods instead

2022-11-14 05:19 UTC, jyecusch commented on docs/guides/serverless-rest-api-example.md
> +    photo_url = await photo.sign_url(mode=FileMode.WRITE, expiry=3600)
```suggestion
    photo_url = await photo.upload_url(expiry=3600)
```

2022-11-14 05:19 UTC, jyecusch commented on docs/guides/serverless-rest-api-example.md
> +    photo_url = await photo.sign_url(mode=FileMode.READ, expiry=3600)
```suggestion
    photo_url = await photo.download_url(expiry=3600)
```

2022-11-14 05:19 UTC, jyecusch commented on docs/guides/serverless-rest-api-example.md
> +    photo_url = await photo.sign_url(mode=FileMode.READ, expiry=3600)
```suggestion
    photo_url = await photo.download_url(expiry=3600)
```

2022-11-18 04:09 UTC, tjholm submitted a review, later dismissed

2022-11-18 04:20 UTC, jyecusch approved these changes

2022-11-18 04:21 UTC, merged