wip: graphql python guide
nitrictech/docs pull request #354
Opened 2022-11-15 16:45 UTC by raksiv

2022-11-17 00:19 UTC, HomelessDinosaur requested changes
Just adding graphql for the syntax highlighting. Should be currently supported in our website by Markdoc so no need to make website changes: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js#L22

2022-11-17 00:19 UTC, HomelessDinosaur commented on docs/guides/graphql.md
> +```
```suggestion
```graphql
updateProfile(pid: String!, profile: ProfileInput!): Profile
```
```

2022-11-17 00:19 UTC, HomelessDinosaur commented on docs/guides/graphql.md
> +```text
```suggestion
```graphql
```

2022-11-17 00:19 UTC, HomelessDinosaur commented on docs/guides/graphql.md
> +```text
```suggestion
```graphql
```

2022-11-17 00:24 UTC, HomelessDinosaur approved these changes

2022-11-18 15:32 UTC, raksiv commented
@HomelessDinosaur I just had to add the nitric start command to the guide.

2022-11-21 04:13 UTC, HomelessDinosaur approved these changes

2022-11-24 22:31 UTC, HomelessDinosaur approved these changes

2022-11-27 22:46 UTC, merged