update documentation with new provider config
nitrictech/docs pull request #385
Opened 2023-04-03 00:26 UTC by HomelessDinosaur

2023-04-03 00:31 UTC, tjholm commented on docs/reference/cli/stacks.md
> +provider: nitric/aws@0.22.1
bump this to latest prod version

2023-04-03 01:45 UTC, jyecusch requested changes

2023-04-03 01:45 UTC, jyecusch commented on docs/deployment.md
> +- `provisioned-concurrency`: The amount of lambdas that should remain provisioned for immediate invocation. Defaults to 0.
```suggestion
- `provisioned-concurrency`: The number of lambda instances that should remain warm for immediate invocation. Defaults to 0.
```

2023-04-19 23:47 UTC, tjholm commented on docs/deployment.md
> +      telemetry: 10
telemetry is top level for the category

2023-04-19 23:47 UTC, tjholm commented on docs/deployment.md
> +    target: lambda
target is no longer used I think (need to test this to make sure)

2023-04-19 23:51 UTC, davemooreuws approved these changes

2023-05-01 03:59 UTC, tjholm approved these changes

2023-05-01 03:59 UTC, merged