Add examples in reference to defining middleware for node and python
nitrictech/docs pull request #389
Opened 2023-04-06 15:45 UTC by raksiv

2023-04-11 01:10 UTC, jyecusch approved these changes

2023-05-02 04:02 UTC, davemooreuws requested changes

2023-05-02 04:02 UTC, davemooreuws commented on docs/reference/nodejs/v0/api/api.md
> +  next();
change to next(ctx)

2023-05-02 23:20 UTC, davemooreuws approved these changes

2023-05-04 22:37 UTC, tjholm commented on docs/reference/nodejs/v0/api/api.md
> +```
should this example also be async like the python examples?

```suggestion
```javascript
const authMiddleware = async (ctx, next) => {
  // Perform auth validation.
  return await next(ctx);
};
```
```

2023-05-11 21:34 UTC, tjholm approved these changes

2023-05-11 23:10 UTC, davemooreuws commented
@tjholm just run format and all good.

2023-05-11 23:22 UTC, davemooreuws approved these changes

2023-05-11 23:25 UTC, merged