Feature/documents service
nitrictech/docs pull request #39
Opened 2021-07-23 02:07 UTC by davemooreuws

Document service docs and api updates

2021-07-26 02:00 UTC, jyecusch requested changes

2021-07-26 05:54 UTC, davemooreuws commented on docs/documents.mdx
> +> Check back soon! We are working on it ⚠️
Maybe it is best to just remove this heading for now? Then add back in when we can actually merge from set?

All other docs I have read keep override documents away from update documents.

2021-07-29 01:58 UTC, jyecusch requested changes

2021-07-29 01:58 UTC, jyecusch commented on docs/events.mdx
> +  await eventsClient.publish('my-topic', {
Shouldn't this be `eventsClient.topic('my-topic').publish(...`?

2021-07-29 01:58 UTC, jyecusch commented on docs/events.mdx
> +  await eventsClient.publish('my-topic', {
`eventsClient.topic('my-topic').publish` ?

2021-08-02 04:18 UTC, jyecusch approved these changes

2021-08-02 04:19 UTC, merged