docs: Update unit testing docs.
nitrictech/docs pull request #402
Opened 2023-06-02 04:48 UTC by tjholm

2023-06-02 09:51 UTC, jyecusch requested changes

2023-06-02 09:51 UTC, jyecusch commented on docs/testing.md
> +export const imageWriter = imageBucket.for('writing');
This isn't imported by the handlers, but they need it.

2023-06-07 12:39 UTC, HomelessDinosaur approved these changes

2023-06-22 06:35 UTC, closed without merging

2023-06-22 06:36 UTC, HomelessDinosaur commented
Closing PR, reopened with a rebase on the new docs page. New PR: https://github.com/nitrictech/docs/pull/411