docs: AWS Provider domain and VPC configuration
nitrictech/docs pull request #428
Opened 2023-07-09 23:40 UTC by tjholm

2023-07-09 23:52 UTC, davemooreuws submitted a review, later dismissed

2023-07-10 00:53 UTC, jyecusch requested changes

2023-07-10 00:53 UTC, jyecusch commented on src/pages/reference/providers/aws/configuration.mdx
> +    # Array of domains to apply the the API
```suggestion
    # Array of domains to apply to the API
```

2023-07-11 20:31 UTC, raksiv approved these changes

2023-07-12 03:19 UTC, davemooreuws approved these changes

2023-07-12 03:20 UTC, merged