add node.js websockets reference docs
nitrictech/docs pull request #446
Opened 2023-08-16 05:42 UTC by jyecusch

2023-08-16 05:43 UTC, tjholm commented on src/pages/reference/nodejs/v0/websocket/websocket-send.mdx
> +}
not javascript, either need to update the annotation or remove the data types.

2023-08-16 05:50 UTC, davemooreuws requested changes
Looks pretty good! Just some suggestions and questions.

2023-08-16 05:50 UTC, davemooreuws commented on src/pages/reference/nodejs/v0/websocket/websocket-close.mdx
> +    The ID of the connection which should be closed.
```suggestion
    The ID of the connection to be closed.
```

2023-08-16 05:50 UTC, davemooreuws commented on src/pages/reference/nodejs/v0/websocket/websocket-on.mdx
Looks good. Might be worth adding that query parameters can only be accessed on connect event.

2023-08-16 05:50 UTC, davemooreuws commented on src/pages/reference/nodejs/v0/websocket/websocket-send.mdx
> +  await socket.send(connectionId, enc.encode(message))
Do we need the enc.encode? I thought alot of this was handled internally

2023-08-16 05:50 UTC, davemooreuws commented on src/pages/reference/nodejs/v0/websocket/websocket-send.mdx
> +    new Promise() <
Weird formatting

2023-08-17 00:30 UTC, HomelessDinosaur submitted a review, later dismissed

2023-08-18 04:23 UTC, tjholm approved these changes

2023-08-18 05:02 UTC, davemooreuws approved these changes

2023-08-18 05:10 UTC, merged