update debugging and testing guides
nitrictech/docs pull request #451
Opened 2023-08-21 06:26 UTC by jyecusch

2023-08-21 06:31 UTC, davemooreuws approved these changes

2023-08-21 06:57 UTC, HomelessDinosaur requested changes

2023-08-21 06:57 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/nodejs/testing.mdx
> +Now we can start writing test. First create a `test` test directory, then add a test file to it named `integration.test.ts`. For the test, we want to create an agent using supertest, then point the a
```suggestion
Now we can start writing the test. First create a `test` test directory, then add a test file to it named `integration.test.ts`. For the test, we want to create an agent using supertest, then point the agent at the URL of our API.
```

2023-08-22 02:06 UTC, HomelessDinosaur approved these changes

2023-08-22 02:12 UTC, tjholm approved these changes

2023-08-22 02:12 UTC, merged