update node.js rest API guide
nitrictech/docs pull request #452
Opened 2023-08-22 06:00 UTC by jyecusch

2023-08-22 06:01 UTC, tjholm submitted a review, later dismissed

2023-08-22 23:33 UTC, HomelessDinosaur requested changes

2023-08-22 23:33 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/nodejs/serverless-rest-api-example.mdx
> +There is also an extended section of the guide that adds file operations using a Nitric [bucket](/buckets) to store and retrieve profile pictures. The extension adds these routes to the API:
```suggestion
There is also an extended section of the guide that adds file operations using a Nitric [bucket](/storage) to store and retrieve profile pictures. The extension adds these routes to the API:
```

2023-08-23 00:32 UTC, HomelessDinosaur approved these changes

2023-08-23 00:38 UTC, davemooreuws approved these changes

2023-08-23 00:46 UTC, merged