Jvm docs
nitrictech/docs pull request #453
Opened 2023-08-23 23:09 UTC by HomelessDinosaur

2023-09-10 23:43 UTC, tjholm approved these changes

2023-09-10 23:57 UTC, davemooreuws requested changes
Looks good to me, add to [Libraries](https://nitric-docs-git-jvm-docs-nitrictech.vercel.app/docs#libraries).

2023-09-11 01:27 UTC, davemooreuws approved these changes

2023-09-12 05:02 UTC, jyecusch submitted a review, later dismissed

2023-09-12 05:23 UTC, davemooreuws requested changes

2023-09-12 05:23 UTC, davemooreuws commented on src/pages/reference/jvm/v0/api/api-post.mdx
> +  [api().route().post]()](./api-route-post)
```suggestion
  [api().route().post()](./api-route-post)
```

2023-09-12 05:23 UTC, davemooreuws commented on src/pages/reference/jvm/v0/api/api-put.mdx
> +  [api().route().put]()](./api-route-put)
```suggestion
  [api().route().put()](./api-route-put)
```

2023-09-12 05:24 UTC, jyecusch approved these changes

2023-09-12 05:26 UTC, davemooreuws approved these changes

2023-09-12 05:51 UTC, merged