encore comparison
nitrictech/docs pull request #469
Opened 2023-09-11 07:04 UTC by davemooreuws

2023-09-11 09:02 UTC, HomelessDinosaur submitted a review, later dismissed

2023-09-11 09:02 UTC, HomelessDinosaur commented on src/pages/faq/comparison/encore.mdx
> +The code snippet using Nitric showcases an API where HTTP request handling is achieved using faas.HttpContext, providing explicit control over the request and response objects. The code snippet using
```suggestion
The code snippet using Nitric showcases an API where HTTP request handling is achieved using `faas.HttpContext`, providing explicit control over the request and response objects. However, the code snippet using Encore demonstrates an API where HTTP request handling is reflected through the function parameters and return types, with a specific emphasis on using defined structs for responses.
```

2023-09-12 00:30 UTC, jyecusch requested changes

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +1. **Cloud Provider Support:** Nitric is provider-agnostic, capable of deploying to multiple cloud providers such as AWS, Google Cloud, and Azure. Encore currently only deploys to AWS or Google Cloud
```suggestion
1. **Cloud Provider Support:** Nitric is provider-agnostic, capable of deploying to multiple cloud providers such as AWS, Google Cloud, and Azure. Encore currently deploys to AWS or Google Cloud.
```

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +2. **Language Support:** Nitric provides multiple libraries for TypeScript/JavaScript, Python, Go, C# .NET and Java, allowing developers to choose their preferred language. Currently Encore only supp
```suggestion
2. **Language Support:** Nitric provides libraries for TypeScript/JavaScript, Python, Go, C# .NET and Java, allowing developers to choose their preferred language. Currently Encore supports Go, with TypeScript scheduled for Preview.
```

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +3. **Infrastructure Provisioning:** Nitric uses Pulumi by default for provisioning cloud resources, but also allows the use of [custom providers](/reference/providers/custom/building-custom-provider)
```suggestion
3. **Infrastructure Provisioning:** Nitric uses Pulumi by default for provisioning cloud resources, but also allows the use of [custom providers](/reference/providers/custom/building-custom-provider). Encore uses a hosted provisioning engine via their online platform.
```

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +4. **Open Source:** As an open-source framework, Nitric itself is free and does not require a proprietary platform to deploy your applications.
```suggestion
4. **Open Source:** As an open-source framework, Nitric does not require a platform or subscription to deploy applications.
```

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +The code snippet using Nitric showcases an API where HTTP request handling is achieved using `faas.HttpContext`, providing explicit control over the request and response objects. However, the code sn
```suggestion
The Nitric example shows an API where HTTP request handling is achieved using `faas.HttpContext`, providing control over the request and response objects. The Encore example demonstrates an API where HTTP request handling is reflected through the function parameters and return types, with defined structs for responses.
```

2023-09-12 00:30 UTC, jyecusch commented on src/pages/faq/comparison/encore.mdx
> +| Provisioning engine  | Pulumi by default, other custom providers can be created                                     | Proprietary provisioning engine |
```suggestion
| Provisioning engine  | Pulumi by default, other custom providers can be created                                     | Hosted provisioning engine |
```

2023-09-12 00:44 UTC, HomelessDinosaur approved these changes

2023-09-12 00:45 UTC, jyecusch approved these changes

2023-09-12 00:56 UTC, merged