feat: add gitlab ci guide
nitrictech/docs pull request #483
Opened 2023-10-26 05:44 UTC by HomelessDinosaur

Closes: https://github.com/nitrictech/nitric/issues/503

2023-10-29 22:16 UTC, jyecusch approved these changes

2023-10-30 03:50 UTC, davemooreuws requested changes

2023-10-30 03:50 UTC, davemooreuws commented on src/pages/guides/getting-started/gitlab-ci.mdx
> +    PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
```suggestion
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_CONFIG_PASSPHRASE
```

2023-10-30 04:10 UTC, davemooreuws commented
I seemed to deploy just fine with this slightly smaller config:

```yaml
deploy:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_CONFIG_PASSPHRASE
    PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    HOST_DOCKER_INTERNAL_IFACE: "eth0"
  before_script:
    - apk update
    - apk add --no-cache curl bash
    - curl https://nitric.io/install | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - curl -fsSL https://get.pulumi.com/ | bash
    - export PATH=$PATH:$HOME/.pulumi/bin
  script:
    - nitric up --ci -v2
```

2023-10-31 00:33 UTC, davemooreuws commented on src/pages/guides/getting-started/gitlab-ci.mdx
> +    - pulumi login
```suggestion
```

2023-11-01 00:48 UTC, jyecusch approved these changes

2023-11-01 01:32 UTC, davemooreuws submitted a review, later dismissed

2023-11-01 01:36 UTC, jyecusch approved these changes

2023-11-01 02:13 UTC, merged