Scheduled services with Google Sheets/Drive guide
nitrictech/docs pull request #528
Opened 2024-04-04 00:16 UTC by raksiv

2024-04-04 00:35 UTC, davemooreuws requested changes

2024-04-04 00:35 UTC, davemooreuws commented on src/pages/guides/getting-started/python/scheduled-report.mdx
Needs a title

2024-04-04 00:52 UTC, HomelessDinosaur requested changes

2024-04-04 00:52 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +We'll create a scheduled services which will run on a daily basis to create and share a Google Sheets document with another user.
```suggestion
We'll create a scheduled service which will run on a daily basis to create and share a Google Sheets document with another user.
```

2024-04-04 00:52 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +We'll begin coding by in a new file 'services\helpers\google.py',
```suggestion
We'll begin coding in a new file `services\helpers\google.py`,
```

2024-04-04 00:52 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +1. Login in to Google Cloud creating a new project.
```suggestion
1. Login into Google Cloud and create a new project.
```

2024-04-04 00:52 UTC, HomelessDinosaur commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```
```suggestion

```

2024-04-04 03:34 UTC, raksiv commented on src/pages/guides/getting-started/python/scheduled-report.mdx
Added!

2024-04-04 23:42 UTC, davemooreuws approved these changes

2024-04-15 23:06 UTC, HomelessDinosaur submitted a review, later dismissed

2024-04-15 23:30 UTC, jyecusch requested changes

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Create a project directory, initialize a Nitric project, and install necessary Python packages.
```suggestion
First, we'll create a new nitric project and install the necessary Python packages.
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Start by creating a new folder 'helpers' and creating a blank '\_\_init\_\_.py' to identify it as a python package.
```suggestion
Start by creating a new folder inside 'service' named 'helpers' and creating a blank `__init__.py` to identify it as a python package.
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Here we will authenticate against Google's API and ensure that our application has the necessary permissions.
```suggestion
We'll begin coding in a new file `services\helpers\google.py`, creating a function that can authenticate with Google's API and ensure our application has the necessary permissions.
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +        raise Exception("Missing/Invalid credentials.")
```suggestion
        raise ValueError("GOOGLE_APPLICATION_CREDENTIALS is not set, failed to load credentials")
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +## Create, Populate and Share Google Sheet
```suggestion
## Create, populate and share a speadsheet
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +## Project Setup
```suggestion
## Project setup
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python  {{ tag: 'services\helpers\google.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python  {{ tag: 'services\helpers\google.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +    spreadsheet = sheets_service.spreadsheets().create(body=spreadsheet, fields='spreadsheetId').execute()
```suggestion
    body = {'properties': {'title': title}}
    spreadsheet = sheets_service.spreadsheets().create(body=body, fields='spreadsheetId').execute()
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python {{ tag: 'services\helpers\google.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python {{ tag: 'services\helpers\google.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python {{ tag: 'services\helpers\google.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +## Daily Report Schedule
```suggestion
## Daily report schedule
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Create a file named `report.py`, where you'll implement your scheduled task service.
```suggestion
Create a file named `report.py` in the `services` directory, where you'll implement your scheduled task service.
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python
```suggestion
```python {{ tag: 'services\report.py' }}
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +async def process_transactions(ctx):
```suggestion
async def daily_report(ctx):
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +We can now update our environment variables, create a file named `.env` and set the following values.
```suggestion
We can now set environment variables with the values needed for the scheduled reporting to run. Create a file named `.env` in the root of your project and set the variables below, substituting the correct values for your setup.
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Start the Nitric server to emulate cloud services:
```suggestion
Start your project and the Nitric server to emulate cloud services:
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +Without creating a separate IaC project, we can immediately deploy our application to the cloud. To do this start by setting up our credentials and any configuration for the cloud you prefer:
```suggestion
Without creating a separate IaC project, we can immediately deploy our application to the cloud. To do this start by setting up credentials and any configuration for the cloud you prefer:
```

2024-04-15 23:30 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +> Note: You are responsible for staying within the limits of the free tier or any costs associated with deployment.
```suggestion
```

2024-04-16 00:56 UTC, davemooreuws submitted a review, later dismissed

2024-04-16 00:58 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\helpers\google.py' }}
```suggestion
```python {{ tag: 'services/helpers/google.py' }}
```

2024-04-16 00:59 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\helpers\google.py' }}
```suggestion
```python {{ tag: 'services/helpers/google.py' }}
```

2024-04-16 00:59 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\helpers\google.py' }}
```suggestion
```python {{ tag: 'services/helpers/google.py' }}
```

2024-04-16 00:59 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\helpers\google.py' }}
```suggestion
```python {{ tag: 'services/helpers/google.py' }}
```

2024-04-16 00:59 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\report.py' }}
```suggestion
```python {{ tag: 'services/report.py' }}
```

2024-04-16 00:59 UTC, jyecusch commented on src/pages/guides/getting-started/python/scheduled-report.mdx
> +```python {{ tag: 'services\helpers\google.py' }}
```suggestion
```python {{ tag: 'services/helpers/google.py' }}
```

2024-04-16 01:19 UTC, jyecusch approved these changes

2024-04-16 01:43 UTC, davemooreuws approved these changes

2024-04-16 01:43 UTC, merged