feat: Update all the doc entries based on testing done in mega-test
nitrictech/docs pull request #53
Opened 2021-08-03 07:13 UTC by HomelessDinosaur

2021-08-03 07:19 UTC, medgar-nitric commented on docs/documents.mdx
> +Subcollection queries can be created under a collection document's subcollection `collection.document.collection.query`
I would recommend changing the order of the subcollection queries, putting collection.document.collection query first. Then put in comments about not yet implemented for the SDK which don't support this yet.

2021-08-03 22:36 UTC, jyecusch requested changes

2021-08-03 22:36 UTC, jyecusch commented on docs/documents.mdx
> +		value: "node"z
Extra 'z' added at the end of this line by mistake

2021-08-03 22:36 UTC, jyecusch commented on docs/documents.mdx
>  		label: "Node.js",
This label could be updated to "Node" like the others

2021-08-05 03:27 UTC, medgar-nitric approved these changes

2021-08-06 04:01 UTC, jyecusch approved these changes

2021-08-06 04:01 UTC, merged