docs: update env variable docs.
nitrictech/docs pull request #541
Opened 2024-04-14 22:43 UTC by tjholm

2024-04-14 22:58 UTC, jyecusch submitted a review, later dismissed

2024-04-14 23:17 UTC, davemooreuws requested changes
Looks good. Just added env to dictionary.txt

2024-04-16 00:59 UTC, davemooreuws approved these changes

2024-04-16 01:01 UTC, davemooreuws approved these changes

2024-04-16 01:01 UTC, davemooreuws commented on src/pages/assets/env.mdx
> +1. any file you pass in via "--env-file"
```suggestion
2. any file you pass in via "--env-file"
```

2024-04-16 01:03 UTC, davemooreuws approved these changes

2024-04-16 01:24 UTC, merged