docs: document preview features
nitrictech/docs pull request #543
Opened 2024-04-17 02:03 UTC by jyecusch

Merge after https://github.com/nitrictech/cli/pull/722 since this documents that preview feature

2024-04-17 03:00 UTC, HomelessDinosaur requested changes

2024-04-18 01:50 UTC, davemooreuws requested changes

2024-04-18 01:50 UTC, davemooreuws commented on src/nav.config.ts
There needs to be an additional bit of a code here to ensure the nav looks correct when on the preview page.

See the other nav items for details on how to do it, basically needs more nav items for preview features.

2024-04-18 01:50 UTC, davemooreuws commented on src/pages/reference/preview-features/cli-preview-features.mdx
Delete this file?

2024-04-18 03:36 UTC, davemooreuws approved these changes

2024-04-22 00:29 UTC, merged