Refresh the contributions page, use more community focussed language.
nitrictech/docs pull request #552
Opened 2024-05-30 16:00 UTC by raksiv

2024-06-03 02:22 UTC, davemooreuws requested changes

2024-06-03 02:22 UTC, davemooreuws commented on src/pages/contributions.mdx
> +For detailed instructions on reporting bugs, refer to the [Creating Bug Reports guide](https://github.com/nitrictech/nitric/blob/main/CONTRIBUTING.md#bug-reports).
```suggestion
For detailed instructions on reporting bugs, refer to the [Creating Bug Reports guide](/support#bug-reports).
```

2024-06-03 16:48 UTC, elisselockhart approved these changes

2024-06-04 23:07 UTC, davemooreuws approved these changes

2024-06-04 23:09 UTC, merged