wip: add build with nitric page
nitrictech/docs pull request #556
Opened 2024-06-04 20:00 UTC by raksiv

2024-06-04 21:16 UTC, elisselockhart requested changes

2024-06-04 21:16 UTC, elisselockhart commented on src/pages/concepts/build-with-nitric.mdx
> +## Data capture applications
```suggestion
## Data capture
```

2024-06-04 21:16 UTC, elisselockhart commented on src/pages/concepts/build-with-nitric.mdx
> +## Data science/analysis processes
```suggestion
## Data science
```

2024-06-04 21:16 UTC, elisselockhart commented on src/pages/concepts/build-with-nitric.mdx
> +## VOD/Live Stream applications
```suggestion
## VOD/Live Stream
```

2024-06-04 21:16 UTC, elisselockhart commented on src/pages/concepts/build-with-nitric.mdx
> +## Multi-tenant SaaS ID verification
```suggestion
## ID verification
```

2024-06-04 21:16 UTC, elisselockhart commented on src/pages/concepts/build-with-nitric.mdx
> +## AI Chatbot
```suggestion
## AI chatbot
```

2024-06-05 00:16 UTC, davemooreuws approved these changes

2024-06-05 00:20 UTC, merged