docs: add detail about legacy SDKs
nitrictech/docs pull request #570
Opened 2024-06-19 03:40 UTC by jyecusch

2024-06-19 03:51 UTC, davemooreuws requested changes

2024-06-19 03:51 UTC, davemooreuws commented on src/components/Layout.tsx
> +                    <Link className="ml-1" href="/#libraries">
This link goes to a component that still has the legacy sdks on it. Could just remove the link and suggest using the command only.

2024-06-21 00:43 UTC, davemooreuws commented
Updated the badges for legacy sdks to "coming soon"

2024-06-21 03:21 UTC, tjholm approved these changes

2024-06-21 03:21 UTC, davemooreuws approved these changes

2024-06-21 03:21 UTC, merged