docs: Python SQL Database docs
nitrictech/docs pull request #583
Opened 2024-07-10 01:44 UTC by tjholm

2024-07-10 02:19 UTC, davemooreuws requested changes

2024-07-10 02:19 UTC, davemooreuws commented on src/pages/reference/python/sql/sql-connection-string.mdx
> +# Python - sql.connection*string*()
```suggestion
# Python - sql.connection_string()
```

2024-07-11 04:26 UTC, HomelessDinosaur commented on src/pages/reference/python/sql/sql.mdx
> +    A reference to migrations to run against the database.
```suggestion
    Points to the location of migration files, prefixed with `file://`, or a
    migration dockerfile, prefixed with `dockerfile://`.
```

2024-07-11 04:29 UTC, HomelessDinosaur approved these changes

2024-07-11 04:32 UTC, davemooreuws approved these changes

2024-07-11 04:48 UTC, merged