feat: add dart middleware to api docs
nitrictech/docs pull request #599
Opened 2024-08-13 14:35 UTC by HomelessDinosaur

Requires: https://github.com/nitrictech/dart-sdk/pull/33

2024-08-14 04:35 UTC, HomelessDinosaur commented
Just going to add middleware documentation to the dart api reference

2024-10-17 04:32 UTC, davemooreuws requested changes

2024-10-17 04:32 UTC, davemooreuws commented on docs/reference/dart/api/api-all.mdx
Add this link to the nav

2024-10-17 04:39 UTC, davemooreuws requested changes

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-get.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-patch.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-post.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-put.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-all.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-delete.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-get.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-patch.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-post.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route-put.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:39 UTC, davemooreuws commented on docs/reference/dart/api/api-route.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 04:52 UTC, davemooreuws requested changes

2024-10-17 04:52 UTC, davemooreuws commented on docs/reference/dart/api/api-delete.mdx
> +import '../middlewares';
```suggestion
```

2024-10-17 05:12 UTC, davemooreuws approved these changes

2024-10-24 23:59 UTC, jyecusch approved these changes

2024-10-24 23:59 UTC, jyecusch commented on docs/reference/dart/api/api-all.mdx
> +    The middleware service to use as the handler for HTTP requests.
```suggestion
    The callback function to use as the handler for HTTP requests.
```

2024-10-24 23:59 UTC, merged