docs: Update GCP configuration reference for GPU config
nitrictech/docs pull request #606
Opened 2024-08-22 03:09 UTC by tjholm

2024-08-22 03:20 UTC, HomelessDinosaur requested changes

2024-08-22 03:20 UTC, HomelessDinosaur commented on src/pages/reference/providers/gcp/configuration.mdx
> +      # https://cloud.google.com/run/docs/configuring
```suggestion
      # https://cloud.google.com/run/docs/configuring/services/cpu
```

2024-08-22 03:20 UTC, HomelessDinosaur commented on src/pages/reference/providers/gcp/configuration.mdx
> +      # https://cloud.google.com/run/docs/configuring
```suggestion
      # https://cloud.google.com/run/docs/configuring/services/gpu
```

2024-08-22 03:20 UTC, HomelessDinosaur commented on src/pages/reference/providers/gcp/configuration.mdx
>        # https://cloud.google.com/run/docs/configuring/memory-limits
```suggestion
      # https://cloud.google.com/run/docs/configuring/services/memory-limits
```

2024-09-25 03:40 UTC, HomelessDinosaur approved these changes

2024-09-25 04:09 UTC, HomelessDinosaur approved these changes

2024-09-25 04:20 UTC, davemooreuws approved these changes

2024-09-25 04:21 UTC, merged