docs: AI podcast guide part 1
nitrictech/docs pull request #641
Opened 2024-10-15 07:08 UTC by tjholm

2024-10-16 04:58 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-1.mdx
> +title_seo: 'Building AI Workflows: Combining LLMs and Voice Models - Part 1'
This only needs to be here if different to the first title in page

2024-10-23 04:52 UTC, davemooreuws requested changes

2024-10-25 00:01 UTC, davemooreuws requested changes

2024-10-25 00:01 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-1.mdx
> +tags:
add languages and maybe start steps (if applicable)

2024-10-25 01:31 UTC, davemooreuws submitted a review, later dismissed

2024-10-25 01:37 UTC, jyecusch submitted a review, later dismissed

2024-10-25 07:09 UTC, merged