Update aws cfg ephemeral templates for pulumi and terraform
nitrictech/docs pull request #650
Opened 2024-10-22 16:34 UTC by raksiv

```
# set the amount of ephemeral-storage: of 512MB
# For info on ephemeral-storage for AWS Lambda see:
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-ephemeral-storage.html
ephemeral-storage: 512
```

2024-10-22 21:14 UTC, jyecusch requested changes

2024-10-22 21:14 UTC, jyecusch commented on docs/providers/pulumi/aws/configuration.mdx
> +      # set the amount of ephemeral-storage: of 512MB
```suggestion
      # set the amount of ephemeral-storage in MB
```

2024-10-22 21:14 UTC, jyecusch commented on docs/providers/pulumi/aws/configuration.mdx
> +      # set the amount of ephemeral-storage: of 512MB
```suggestion
      # set the amount of ephemeral-storage in MB
```

2024-10-22 21:14 UTC, jyecusch commented on docs/providers/terraform/aws.mdx
>        # For info on provisioned concurrency for AWS Lambda see:
Can you update the comments here, it looks like there weren't quite right before this PR so it's a good chance to clean them up

2024-10-23 01:14 UTC, tjholm approved these changes

2024-10-24 23:04 UTC, jyecusch approved these changes

2024-10-24 23:04 UTC, merged