docs: ai podcast guide part 2
nitrictech/docs pull request #653
Opened 2024-10-29 01:55 UTC by jyecusch

2024-11-01 01:12 UTC, davemooreuws requested changes
Some changes to the yaml for windows

2024-11-01 01:12 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-2.mdx
> +    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R python -- -u $SERVICE_PATH
```suggestion
    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R uv run $SERVICE_PATH
```

2024-11-01 01:12 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-2.mdx
> +    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R python -- -u $SERVICE_PATH
```suggestion
    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R uv run $SERVICE_PATH
```

2024-11-01 01:12 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-2.mdx
> +    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R python -- -u $SERVICE_PATH
```suggestion
    start: uv run watchmedo auto-restart -p *.py --no-restart-on-command-exit -R uv run $SERVICE_PATH
```

2024-11-01 02:46 UTC, davemooreuws requested changes

2024-11-01 02:46 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-2.mdx
> +  await generate_podcast.submit({"title": title, "prompt": body.decode('utf-8')})
need to define generate_podcast above as a diff +

2024-11-01 03:01 UTC, davemooreuws commented
Noticed there isn't any screenshots or steps for running it locally like there was in part 1. Is this something we want to add? @jyecusch

2024-11-04 03:01 UTC, tjholm submitted a review, later dismissed

2024-11-04 05:06 UTC, davemooreuws requested changes

2024-11-04 05:06 UTC, davemooreuws commented on docs/guides/python/ai-podcast-part-2.mdx
> +# diff +
```suggestion
# !diff +
```

2024-11-07 04:47 UTC, davemooreuws approved these changes

2024-11-08 00:03 UTC, tjholm approved these changes

2024-11-08 00:03 UTC, merged