docs: Locating resources deployed by nitric
nitrictech/docs pull request #654
Opened 2024-10-29 04:56 UTC by tjholm

Have added documentation to the AWS, Azure and AWSTF provider pages on centrally locating resources deployed by each of these providers on their index pages.

2024-10-29 23:54 UTC, jyecusch requested changes

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/aws/index.mdx
> +Nitric creates a resource tag manager group and tags all possible resources to be referenced by this group. You can locate resources in the console by going to the [AWS Console](https://console.aws.a
```suggestion
This Nitric AWS provider creates a resource tag manager group and tags all possible resources to be referenced by this group. You can locate resources using the [AWS Console](https://console.aws.amazon.com/).
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/aws/index.mdx
> +Navigate to the resource groups service:
```suggestion
Start by navigating to the [Resource Groups service](https://console.aws.amazon.com/resource-groups/home):
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/aws/index.mdx
> +So in the example above, the project name is `api-testing` and the stack name is `aws`.
```suggestion
Find your stack's resource group in the list and click it:

<Note>
  Resource groups are conventionally named `<project-name>-<stack-name>`

  In this example the project name is `api-testing` and the stack name is `aws`.
</Note>

![resource group list image](/docs/images/docs/aws-rg-screen.png)
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/aws/index.mdx
> +More recent versions of the Nitric AWS provider also output a direct link to it's resource group in the console from running `nitric up`
```suggestion
More recent versions of the Nitric AWS provider also display a direct link to the resource group in output from `nitric up`.
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/aws/index.mdx
> +## Locating resources deployed with Nitric
```suggestion
## Locating deployed resources
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/azure/index.mdx
> +## Locating resources deployed with Nitric
```suggestion
## Locating deployed resources
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/azure/index.mdx
> +Nitric deploys all Azure resources for a stack into a resource group dedicated to that stack. You can either use one your already have by configuring it in the stack configuration or let Nitric creat
```suggestion
This Nitric Azure provider deploys resources for a stack into a resource group dedicated to that stack. You can either use one your already have by configuring it in the stack configuration or let Nitric create one for you.
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/azure/index.mdx
> +Once a nitric stack is deployed to azure it's resource group should be present in the [Resource groups](https://portal.azure.com/#blade/HubsExtension/BrowseResourceGroupBlade/resourceType/Microsoft.R
```suggestion
Once a stack has been deployed to Azure it's resource group should be present in the [Resource groups](https://portal.azure.com/#blade/HubsExtension/BrowseResourceGroupBlade/resourceType/Microsoft.Resources%2Fsubscriptions%2FresourceGroups) page of the portal. Assuming it was deployed to a subscription you have access to.
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/azure/index.mdx
> +So in the example above, the project name is `api-testing` and the stack name is `az`.
```suggestion
<Note>
  Resource groups are conventionally named `<project-name>-<stack-name>-<randomId>`

  In this example the project name is `api-testing` and the stack name is `az`.
</Note>

![resource group page screen](/docs/images/docs/az-rg.png)
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/pulumi/azure/index.mdx
> +More recent versions of the Nitric Azure provider also output a direct link to it's resource group in the console from running `nitric up`
```suggestion
More recent versions of the Nitric Azure provider display a direct link to the resource group in output from `nitric up`.
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/terraform/aws.mdx
> +## Locating resources deployed with Nitric
```suggestion
## Locating deployed resources
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/terraform/aws.mdx
> +Navigate to the resource groups service:
```suggestion
Next, navigate to the [Resource Groups service](https://console.aws.amazon.com/resource-groups/home):
```

2024-10-29 23:54 UTC, jyecusch commented on docs/providers/terraform/aws.mdx
> +
```suggestion
Find your stack's resource group in the list and click it:

<Note>
  Resource groups are conventionally named `<project-name>-<stack-name>`

  In this example the project name is `api-testing` and the stack name is `aws`.
</Note>

![resource group list image](/docs/images/docs/aws-rg-screen.png)
```

2024-10-30 00:20 UTC, jyecusch approved these changes

2024-10-30 04:00 UTC, HomelessDinosaur approved these changes

2024-10-30 04:02 UTC, merged