feat: open ai whisper guide
nitrictech/docs pull request #659
Opened 2024-11-05 06:14 UTC by HomelessDinosaur

2024-11-05 21:46 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +|      +--main.py
```suggestion
|      +--services.py
```

2024-11-05 21:47 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> ++--src/
was there a reason for using a src directory here?

2024-11-05 21:47 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +|      +--api.pypy
```suggestion
|  +--jobs/
|      +--transcribe.py
```

2024-11-05 21:49 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +We'll then load our model and transcribe the audio. This is where we can choose the model based on balancing speed, size, and accuracy. We can turn off `FP16` with `fp16=False` which will use `FP32`
Why is Lambda referenced here?

2024-11-05 21:56 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +
Could we use codehike features here rather than splitting into two sections?

2024-11-05 21:59 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +</Note>
is this accurate?

2024-11-05 23:36 UTC, tjholm commented on docs/guides/python/podcast-transcription.mdx
> +```
Working through the guide, the doubling up of code blocks was a bit confusing in some cases. Is there a way we could merge them and integrate the explanation into the code block itself?

2024-11-11 23:14 UTC, jyecusch commented on docs/guides/python/podcast-transcription.mdx
> +
```suggestion

Now, let's run the script to download the model. We'll start by making sure we're using the venv uv created.

```bash
source .venv/bin/activate

uv run download_model.py --model_name turbo
```

```

2024-11-15 03:00 UTC, jyecusch approved these changes

2024-11-15 06:05 UTC, davemooreuws requested changes

2024-11-15 06:06 UTC, davemooreuws approved these changes

2024-11-18 01:57 UTC, jyecusch approved these changes

2024-11-18 01:57 UTC, merged