fix: remove old error handling on resource creation
nitrictech/docs pull request #661
Opened 2024-11-08 04:47 UTC by HomelessDinosaur

2024-11-08 04:49 UTC, davemooreuws requested changes

2024-11-08 04:49 UTC, davemooreuws commented on docs/index.mdx
>  	profiles, _ := nitric.NewBucket("profiles").Allow(nitric.BucketRead, nitric.BucketWrite, nitric.BucketDelete)
```suggestion
	profiles := nitric.NewBucket("profiles").Allow(nitric.BucketRead, nitric.BucketWrite, nitric.BucketDelete)
```

2024-11-11 00:54 UTC, jyecusch approved these changes

2024-11-11 01:40 UTC, davemooreuws approved these changes

2024-11-11 01:40 UTC, merged