refresh documentation
nitrictech/docs pull request #693
Opened 2024-12-30 05:21 UTC by HomelessDinosaur

2025-01-05 23:13 UTC, davemooreuws requested changes

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/byo-database.mdx
> +- For local development is to set up a container that runs alongside your Nitric processes.
```suggestion
- For local development, set up a container that runs alongside your Nitric processes.
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/byo-database.mdx
> +- For a production environment, you can use any of the database services for your preferred cloud:
```suggestion
- For a production environment, use any of the database services offered by your preferred cloud provider:
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/expressjs.mdx
add bash highlighting to code block that contains:

```
cd express-example
yarn install
yarn add express
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/fastify.mdx
>  In this structure you'll notice the `servuces` folder. By default, this is where Nitric expects the entrypoint code for your application. However, that's just a convention, we can change that to anyt
```suggestion
In this structure you'll notice the `services` folder. By default, this is where Nitric expects the entrypoint code for your application. However, that's just a convention, we can change that to anything else that suits our needs.
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/fastify.mdx
> +```javascript title:services/app.js
```suggestion
```javascript title:services/api.js
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/fastify.mdx
>  You can update the `app.js` file like so:
```suggestion
You can update the `api.js` file like so:
```

2025-01-05 23:13 UTC, davemooreuws commented on docs/guides/nodejs/fastify.mdx
> +```javascript title:services/app.js
```suggestion
```javascript title:services/api.js
```

2025-01-08 01:40 UTC, davemooreuws approved these changes

2025-01-09 00:18 UTC, raksiv approved these changes

2025-01-09 04:20 UTC, merged